### ISSUE TITLE
nLTT incompatible with R 3.6.0

### ISSUE THREAD

**Issue by thijsjanzen** [thijsjanzen/nLTT#42]
It seems that nLTT does not run under R 3.6.0 I suspect it is to do with Issue #41

**Comment by richelbilderbeek** [comment]
Nah, DDD needs 3.6.0. I already added a [Pull Request](https://github.com/rsetienne/DDD/pull/8).

As a workaround, we could use my fork.

**Comment by thijsjanzen** [comment]
Does this issue still persist?

**Comment by richelbilderbeek** [comment]
AFAIK now. Go each and close this Issue: we'll re-open iff the problem appears to persist :shipit:
