### ISSUE TITLE
Add log transform number of lineages option

### ISSUE THREAD

**Issue by thijsjanzen** [thijsjanzen/nLTT#44]
Add an option (by default FALSE) to log-transform the number of lineages before normalization. This should put weight on differences in deep-time.

**Comment by richelbilderbeek** [comment]
May do, when I need it. I'll unassign myself until then.

**Comment by thijsjanzen** [comment]
I have updated all nLTT functions to include log transformations - see the new branch.
It seems this doesn't generate errors.
However, I have not yet checked all visualization options.

Also, some additional tests might proof valuable.

**Comment by richelbilderbeek** [comment]
Looks good enough to merge to `develop` to me :shipit:!

**Comment by richelbilderbeek** [comment]
I took the liberty to merge to develop, for [pirouette_example_14](https://github.com/richelbilderbeek/pirouette_example_14).

**Comment by thijsjanzen** [comment]
I believe this is included in master now and can be closed @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
Yup! Go ahead and kill that obsolete branch :+1: :shipit:
