### ISSUE TITLE
Fix MacOS build

### ISSUE THREAD

**Issue by richelbilderbeek** [thijsjanzen/nLTT#49]
There's a new error in [the nLTT logs](https://travis-ci.org/richelbilderbeek/nLTT/jobs/597219736#L941).

Something changed upstream for MacOS. I've disabled that Travis builds for MacOS for now, but it would be good to have this error fixed.

**Comment by richelbilderbeek** [comment]
> but really, data.table should fix this, not us

Unsure. Maybe they think clang should fix this, not them :grin:.

In other words: let use get a workaround in place. I suffer the same problem on other of my R repos as well, so if I find a workaround, I will apply it here as well.

**Comment by thijsjanzen** [comment]
I have re-enabled the macos build, and all went fine.
