### ISSUE TITLE
indirect nLTT is not 100% accurate

### ISSUE THREAD

**Issue by thijsjanzen** [thijsjanzen/nLTT#50]
The idea is the following: if you can not calculate d(A, B) (where d = distance, A is a tree and B is a tree), but you can calculate d(A, C) and d(B, C), then d(A, B) = d(A, C) - d(B, C). This should be generally true, but when applying this to nLTT, it is not entirely accurate, especially when A and B are highly similar - it seems there are some accuracy problems.

Consider:
```
# empty tree 'C'
emp_tree <- phytools::read.newick(text = "(1:4,2:4):0;")

# tree A
focal_tree <- TreeSim::sim.bd.taxa(n = 100, numbsim = 1, lambda = 0.5, mu = 0)

# many trees B
comp_trees <- TreeSim::sim.bd.taxa(n = 100, numbsim = 100, lambda = 1, mu = 0)

a <- nLTT::nltt_diff_exact(focal_tree[[1]], emp_tree)

found <- matrix(nrow = length(comp_trees), ncol = 2)
for(i in 1:length(comp_trees)) {
  # this is the exact difference:
  exact_diff <- nLTT::nltt_diff_exact(comp_trees[[i]], focal_tree[[1]])
  
  
  # this is the indirect difference:
  b  <- nLTT::nltt_diff_exact(comp_trees[[i]], emp_tree)
  indirect_diff <- abs(b-a)
  
  found[i, ] <- c(exact_diff, indirect_diff)
}

par(mfrow=c(1,2))
plot(found)
abline(coef = c(0,1))

plot(found[,2] - found[,1])
```

**Comment by thijsjanzen** [comment]
Related to this, shouldn't we make the function 'nltt_diff' point towards 'nltt_diff_exact' ?

**Comment by richelbilderbeek** [comment]
Helpful plot:

![screen](https://user-images.githubusercontent.com/2098230/68786065-7262b800-063f-11ea-843a-07dbd1ad790d.png)

**Comment by richelbilderbeek** [comment]
@thijsjanzen: I would enjoy you'd articulate what is the problem. We know computers make rounding errors :rainbow: . 

Could you supply a test that you would expect to pass, but in reality fail? Those, I can work with for breakfast :sunglasses: !

**Comment by thijsjanzen** [comment]
The question is - are these rounding errors? If they were, shouldn't they be normally distributed?

Basically, using the indirect method, tends to over-estimate the nLTT. 
This is, because the indirect substraction trick only works if the two nLTT lines do not intersect. 
Consider the following instructive example:

```
# we only work with normalized branching times, for simplicity
btimes1 <- seq(0,1, by =0.01)
lineages1 <- btimes1
plot(lineages1~btimes1, type = "s", main = "Surface under LTT = 0.5", 
     xlab = "Normalized time",
     ylab = "Normalized number of lineages")

btimes2 <- c(0, 0.5, 1)
lineages2 <- c(0, 1, 1)

plot(lineages2~btimes2, type = "s", main = "Surface under LTT = 0.5", 
     xlab = "Normalized time",
     ylab = "Normalized number of lineages")

exact_diff <- nLTT::nltt_diff_exact_norm_brts(b_times_n = btimes1,
                                lineages_n = lineages1,
                                b_times2_n = btimes2, 
                                lineages2_n = lineages2,
                                distance_method = "abs")

# reference tree for indirect measurement:
btimes3 <- c(0, 1)
lineages3 <- c(1, 1)

diff1 <- nLTT::nltt_diff_exact_norm_brts(b_times_n = btimes1,
                                lineages_n = lineages1,
                                b_times2_n = btimes3, 
                                lineages2_n = lineages3,
                                distance_method = "abs")


diff2 <- nLTT::nltt_diff_exact_norm_brts(b_times_n = btimes2,
                                lineages_n = lineages2,
                                b_times2_n = btimes3, 
                                lineages2_n = lineages3,
                                distance_method = "abs")

diff1 - diff2
exact_diff
all.equal(diff1-diff2, exact_diff)
```

![ltt_plot](https://user-images.githubusercontent.com/19486664/68803723-9387d080-0660-11ea-9a87-ea6cb3b76d65.jpg)

**Comment by richelbilderbeek** [comment]
> The question is - are these rounding errors?

I think questions are:

 * Are these errors or consequences of computers having finite precision?
 * Do these errors matter?

I think it's nice to rediscover computer have finite precision and rediscovering rounding errors need not be normally distributed, but if it's irrelevant in practice, one should close this Issue.

So, do these errors matter? If yes, how much? If much, will using arbitrary precision floating points solve it (e.g.[mcbette does so](https://github.com/richelbilderbeek/mcbette/blob/master/tests/testthat/test-calc_weights.R#L46))?

If your last note was a note to self: sorry for the unwanted dialog :+1:

**Comment by thijsjanzen** [comment]
Allright, further thinking has alleviated that these are *not* rounding errors, but that the approach is inherently flawed.

The premise:  d(A, B) = d(A, C) - d(B, C), only holds if A > B, that is, if the nLTT curve of A does *not* intersect the nLTT curve of B. If it does, subtracting the two surfaces no longer yields a valid answer. Typically, as two nLTT curves become more similar, they are more likely to cross. Hence the increased error for small nLTT values.

Ergo: nice idea, but simply not possible.
