### ISSUE TITLE
Test last line of code

### ISSUE THREAD

**Issue by richelbilderbeek** [thijsjanzen/nLTT#53]
I see [in the Travis build log](https://travis-ci.org/thijsjanzen/nLTT/jobs/649507034#L1235), there is one line being untested, `R/ABC_SMC.R:266`. Would this line be tested, code coverage would be 100%!

@thijsjanzen: I suggest to either remove the line (as it is not triggered anyways by the test), or write a test to trigger it.

Good idea?

**Comment by thijsjanzen** [comment]
I have opted to remove this line in: https://github.com/thijsjanzen/nLTT/commit/f99096da753ec3ffb3b4c6b831d93f2f7911126b
