### ISSUE TITLE
Add Neves-P to DESCRIPTION as a contributor

### ISSUE THREAD

**Issue by richelbilderbeek** [thijsjanzen/nLTT#54]
@thijsjanzen: I suggest to add @Neves-P to the DESCRIPTION as a contributor for the functions he provided. Doing so is easy, similar to e.g. Giovanni's contribution to babette [here](https://github.com/ropensci/babette/blob/master/DESCRIPTION#L8). 

Sure, I volunteer to do so :+1:

**Comment by thijsjanzen** [comment]
Done in a38f6a4e321490497387d025972953cd227bff31
