### ISSUE TITLE
master broken

### ISSUE THREAD

**Issue by richelbilderbeek** [thijsjanzen/nLTT#56]
Hi @thijsjanzen, on Travis, [master is broken](https://travis-ci.org/github/thijsjanzen/nLTT/jobs/725498361#L5148). Reason is that `lintr` now also checks vignettes for style. Will be an easy fix, I just wanted to make you aware of this :+1:

**Comment by thijsjanzen** [comment]
I know, it happened after I added a sticker to the README.
I will look into this later this week to fix the vignettes.

**Comment by thijsjanzen** [comment]
fixed.
