### ISSUE TITLE
switch to GitHub Actions

### ISSUE THREAD

**Issue by thijsjanzen** [thijsjanzen/nLTT#57]
With the upcoming monetizing moves at TravisCI, I propose to move CI to GitHub Actions.
I have already set up the actions, what remains is removal of Travis.

What do you think @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
I completely agree! I am phasing out Travis CI as well for all my other packages ...

**Comment by thijsjanzen** [comment]
Done
