### ISSUE TITLE
noSuggests CRAN

### ISSUE THREAD

**Issue by thijsjanzen** [thijsjanzen/nLTT#59]
I got an email from CRAN that the package will be archived if we do not resolve the 'noSuggests' issue:

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_nLTT.html>.
> 
> Please correct before 2022-05-21 to safely retain your package on CRAN.
> 
> Packages in Suggests should be used conditionally: see 'Writing R Extensions'.
> This needs to be corrected even if the missing package(s) become available.
> It can be tested by checking with _R_CHECK_DEPENDS_ONLY_=true.
> 
> The CRAN Team

the 'noSuggests' check performs the following:

> Tests on x86_64 Linux with R-devel using _R_CHECK_DEPENDS_ONLY_=true,
> so packages in Suggests (and Enhances) are not available (other
> than recommended packages).
> 
> For this to work as intended, add-on packages need to be installed
> in a library other than .Library.
> 
> Other details as 
> https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-gcc

I don't really understand how this should be resolved - as far as I understand, packages used in tests, should be added to the 'suggests' list and NOT to depends. The R manual (https://cran.r-project.org/doc/manuals/r-release/R-exts.html) says:

> All packages that are needed[12](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#FOOT12) to successfully run R CMD check on the package must be listed in one of ‘Depends’ or ‘Suggests’ or ‘Imports’. Packages used to run examples or tests conditionally (e.g. via if(require(pkgname))) should be listed in ‘Suggests’ or ‘Enhances’. (This allows checkers to ensure that all the packages needed for a complete check are installed.)

Under suggested packages (https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages), I find

> Note that someone wanting to run the examples/tests/vignettes may not have a suggested package available (and it may not even be possible to install it for that platform). The recommendation used to be to make their use conditional via if(require("pkgname")): this is OK if that conditioning is done in examples/tests/vignettes, although using if(requireNamespace("pkgname")) is preferred, if possible.
> 
> However, using require for conditioning in package code is not good practice as it alters the search path for the rest of the session and relies on functions in that package not being masked by other require or library calls. It is better practice to use code like
> 
>    if (requireNamespace("rgl", quietly = TRUE)) {
>       rgl::plot3d(...)
>    } else {
>       ## do something else not involving rgl.
>    }
> Note the use of rgl:: as that object would not necessarily be visible (and if it is, it need not be the one from that namespace: plot3d occurs in several other packages). If the intention is to give an error if the suggested package is not available, simply use e.g. rgl::plot3d.

Which seems like an extremely ugly solution.

@richelbilderbeek  and @Neves-P Do you guys have any idea how this should be resolved?

From the output here: https://www.stats.ox.ac.uk/pub/bdr/noSuggests/nLTT.out, it seems the following code is affected:
```
══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error (test-abc_smc_nltt.R:99:3): abc_smc_nltt abuse ────────────────────────
  <packageNotFoundError/error/condition>
  Error in `loadNamespace(x)`: there is no package called 'TreeSim'
  Backtrace:
      ▆
   1. ├─nLTT treesim(c(1, 0)) at test-abc_smc_nltt.R:99:2
   2. └─base::loadNamespace(x) at test-abc_smc_nltt.R:63:4
   3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
   4.     └─base withOneRestart(expr, restarts[[1L]])
   5.       └─base doWithOneRestart(return(expr), restart)
  ── Error (test-get_average_nltt.R:43:3): nltts_plot: check data types ──────────
  <packageNotFoundError/error/condition>
  Error in `loadNamespace(x)`: there is no package called 'TreeSim'
  Backtrace:
      ▆
   1. └─base::loadNamespace(x) at test-get_average_nltt.R:43:2
   2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
   3.     └─base withOneRestart(expr, restarts[[1L]])
   4.       └─base doWithOneRestart(return(expr), restart)
  ── Error (test-get_average_nltt_matrix.R:147:3): data types ────────────────────
  <packageNotFoundError/error/condition>
  Error in `loadNamespace(x)`: there is no package called 'TreeSim'
  Backtrace:
      ▆
   1. └─base::loadNamespace(x) at test-get_average_nltt_matrix.R:147:2
   2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
   3.     └─base withOneRestart(expr, restarts[[1L]])
   4.       └─base doWithOneRestart(return(expr), restart)
  ── Error (test-mcmc_nltt.R:59:3): mcmc_nltt abuse ──────────────────────────────
  <packageNotFoundError/error/condition>
  Error in `loadNamespace(x)`: there is no package called 'TESS'
  Backtrace:
      ▆
   1. └─base::loadNamespace(x) at test-mcmc_nltt.R:59:2
   2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
   3.     └─base withOneRestart(expr, restarts[[1L]])
   4.       └─base doWithOneRestart(return(expr), restart)
  ── Error (test-style.R:2:3): Package style ─────────────────────────────────────
  <packageNotFoundError/error/condition>
  Error in `loadNamespace(x)`: there is no package called 'lintr'
  Backtrace:
      ▆
   1. └─base::loadNamespace(x) at test-style.R:2:2
   2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
   3.     └─base withOneRestart(expr, restarts[[1L]])
   4.       └─base doWithOneRestart(return(expr), restart)
  ```

**Comment by Neves-P** [comment]
Hey @thijsjanzen 
Following up on our chat in the office, at first glace this really looks like now there is an issue with code calling functions in suggested packages that is not caught by the `requireNamespace()` approach you mention. I recall that on DAISIE on functions we took that approach, see here:
https://github.com/rsetienne/DAISIE/blob/36674127e0451f78372196bf759e11b5f05c9184/R/DAISIE_plot_input.R#L67-L88

I have also just found out about a `testthat` function that seems to be a shorthand for dealing with this when the offending code is only called on tests, which I think should really fit your needs: 😁 

```testthat::skip_if_not_installed("TreeSim")```

**Comment by thijsjanzen** [comment]
Ok, I have now fixed the tests - I use more the (imported) ape simulator where possible, and have used the testthat::skip_if_not_installed flag to fix those where I couldn't.

However, it remains failing (it seems) for rmarkdown, which is used in the Vignettes (I know right).

In this package they seem to have made it work however: https://github.com/SoftwareAG/r-pmml/commit/7b3510645f8221d5901eb1530de820b7a4dcd2f6

I'm also not sure if they really check for the noSuggests issue (which is tested by setting _R_CHECK_DEPENDS_ONLY_ to TRUE, which I have now enabled in the GitHub actions of the develop branch). There might be other ways to do this though.

**Comment by thijsjanzen** [comment]
Ok, it seems to work now (at least when checking locally).
I had to remove the ABC part from the vignette to make it work. This is unfortunate, but it stays online on the GitHub Wiki (although I'm worried that most people will not find that).

**Comment by thijsjanzen** [comment]
I have merged develop with master and submitted this version to CRAN. let's see how it does in their tests.
